# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overwriteDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(330, 136)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 261, 51))
        self.label.setObjectName("label")
        self.yesButton = QtWidgets.QPushButton(Dialog)
        self.yesButton.setGeometry(QtCore.QRect(100, 90, 93, 28))
        self.yesButton.setObjectName("yesButton")
        self.noButton = QtWidgets.QPushButton(Dialog)
        self.noButton.setGeometry(QtCore.QRect(210, 90, 93, 28))
        self.noButton.setObjectName("noButton")

        self.yesButton.clicked.connect(self.accept)
        self.noButton.clicked.connect(self.reject)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "같은 이름의 파일이 이미 존재합니다.\n"
" 파일을 덮어쓰시겠습니까?"))
        self.yesButton.setText(_translate("Dialog", "네"))
        self.noButton.setText(_translate("Dialog", "아니오"))

    def reject(self):
        self.dialog.close()
    def accept(self):
        self.dialog.close()